/* Civics, Grades 7–12. Original supplementary teaching material, not a
   transcription of an official Liberian Civics syllabus or WAEC paper.
   Six progressively themed units per grade. Teachers should compare these
   resources with their school's approved scheme of work before use.
   No personal political affiliation or disclosure is required by activities. */
(function (root) {
  "use strict";
  var glossary = {
    civics: "the study of people's rights, responsibilities and participation in public life",
    community: "people connected by a place, shared interests or common responsibilities",
    citizenship: "membership of a political community, involving rights and responsibilities",
    responsibility: "a duty to act carefully and account for the effects of one's actions",
    respect: "treating people with dignity even when their views or backgrounds differ",
    rule: "an agreed or authorized instruction that guides conduct",
    fairness: "using just reasons and considering relevant needs when making decisions",
    cooperation: "working with others toward a shared purpose",
    inclusion: "making meaningful participation possible for people who might otherwise be excluded",
    discrimination: "unjust unequal treatment based on a person's identity or background",
    identity: "the characteristics and connections through which a person understands who they are",
    diversity: "the presence of different backgrounds, experiences and ways of life",
    dignity: "the inherent worth of every person",
    stereotype: "an oversimplified assumption about everyone in a group",
    dialogue: "a respectful exchange in which people speak and listen to understand one another",
    symbol: "an object, sign or image that represents an idea or community",
    heritage: "practices, places and knowledge passed between generations",
    unity: "working together despite differences",
    patriotism: "care for one's country and its people's well-being",
    service: "work undertaken to meet other people's or a community's needs",
    conflict: "a disagreement involving interests, needs, actions or beliefs",
    mediation: "help from an impartial person who supports others in resolving a dispute",
    compromise: "an agreement in which each side makes a reasonable adjustment",
    empathy: "trying to understand another person's feelings and situation",
    violence: "the use of force or threats to harm or intimidate",
    volunteering: "freely giving time and effort to a useful activity",
    sanitation: "measures that keep surroundings clean and reduce health risks",
    environment: "the natural and human surroundings in which people live",
    resource: "something people can use to meet a need",
    sustainability: "meeting present needs without undermining future people's ability to meet theirs",
    government: "institutions and people authorized to make and carry out public decisions",
    constitution: "the fundamental framework defining a state's institutions and protected rights",
    law: "a binding rule made or recognized through a legitimate legal process",
    authority: "a recognized power to make decisions within defined limits",
    accountability: "the obligation to explain decisions and face appropriate review or consequences",
    legislature: "the branch of government responsible for making laws and exercising legislative oversight",
    executive: "the branch of government responsible for administering laws and public policy",
    judiciary: "the branch of government that interprets laws and resolves legal disputes",
    separation: "the distribution of state powers among different institutions",
    oversight: "checking how power or resources are used",
    county: "a major territorial subdivision of Liberia",
    district: "an administrative or electoral area within a larger territory",
    decentralization: "moving some public responsibilities closer to local communities",
    consultation: "seeking affected people's views before making a decision",
    representation: "acting or speaking on behalf of others while considering their interests",
    democracy: "government in which people participate in choosing leaders and public decisions under rules protecting rights",
    election: "a rule-governed process for choosing representatives or deciding a public question by voting",
    ballot: "a paper or other authorized means of recording a vote",
    manifesto: "a public statement of a candidate's or group's proposed policies",
    participation: "taking part in decisions or activities that affect a community",
    rights: "protected freedoms and entitlements that people may claim",
    liberty: "freedom to act and express oneself within lawful limits that respect others' rights",
    equality: "equal dignity and equal protection rather than automatic sameness in every circumstance",
    privacy: "protection against unjustified intrusion into personal life and information",
    remedy: "a lawful way to seek correction or redress for a wrong",
    tax: "a compulsory payment imposed by law to support public purposes",
    budget: "a plan showing expected income and proposed expenditure",
    revenue: "money received by an organization or government",
    expenditure: "money spent for a stated purpose",
    priority: "a need or goal given greater attention when resources are limited",
    evidence: "information that can support or challenge a claim",
    source: "the person, record or observation from which information comes",
    verification: "checking a claim against reliable and preferably independent evidence",
    misinformation: "false or inaccurate information, whether or not shared intentionally",
    opinion: "a person's judgment or belief, which may need evidence if it makes factual claims",
    consent: "freely given and informed agreement to a specific action",
    safety: "protection from foreseeable harm",
    bullying: "repeated or serious intimidating behavior that exploits a power imbalance",
    accessibility: "designing places or information so people with different needs can use them",
    advocacy: "using reasoned communication to seek a change or defend a public interest",
    petition: "a formal written request supported by one or more people",
    integrity: "acting honestly and consistently with fair ethical standards",
    corruption: "abuse of entrusted power for private benefit",
    transparency: "making relevant decisions, rules and records open to appropriate scrutiny",
    bribery: "offering or receiving an improper benefit to influence a decision",
    restitution: "restoring property or compensating for a loss when appropriate",
    conservation: "protecting and carefully managing natural resources",
    pollution: "harmful contamination of air, land or water",
    resilience: "the ability to prepare for, withstand and recover from difficulty",
    prevention: "action taken to reduce the chance of harm occurring",
    justice: "fair treatment, protection of rights and appropriate responses to wrongdoing",
    testimony: "a person's account of events they experienced or know about",
    reconciliation: "a process of rebuilding relationships after conflict without denying harms",
    dueProcess: "fair procedures before a person is deprived of protected rights or interests",
    presumption: "a starting legal assumption that must be respected unless lawfully displaced by evidence",
    impartiality: "deciding fairly without favoring a person or group for irrelevant reasons",
    appeal: "a request for an authorized body to review a decision",
    amendment: "a formal change made through an authorized procedure",
    referendum: "a direct vote by eligible voters on a public question",
    sovereignty: "a state's authority over its public affairs, subject to its legal commitments",
    legitimacy: "public authority's justified claim to be recognized and obeyed",
    publicInterest: "the shared well-being of the community rather than a private advantage",
    procurement: "the process of acquiring goods or services for an organization",
    audit: "an independent or authorized examination of records and practices",
    conflictOfInterest: "a situation where a private interest may improperly influence a public duty",
    policy: "a proposed or adopted course of action to address an issue",
    indicator: "a measurable sign used to assess progress toward a goal",
    evaluation: "a systematic judgment of how well an activity meets its goals",
    stakeholder: "a person or group affected by or able to affect a decision",
    migration: "movement of people from one place to another to live",
    refugee: "a person outside their country who meets applicable legal criteria for international protection",
    asylum: "protection sought or granted by a state to a person facing qualifying danger elsewhere",
    displacement: "being forced or obliged to leave one's home",
    humanitarian: "concerned with protecting people's lives and dignity in situations of need",
    diplomacy: "communication and negotiation between states or their representatives",
    treaty: "a formal international agreement governed by international law",
    multilateralism: "cooperation involving several countries",
    interdependence: "a relationship in which people or countries affect and depend on one another",
    peacebuilding: "long-term work to reduce causes of conflict and strengthen peaceful institutions",
    trade: "exchange of goods and services",
    development: "improvement in people's capabilities, opportunities and living conditions",
    inequality: "unequal access to resources, opportunities or outcomes",
    entrepreneurship: "organizing an activity or enterprise to meet a need while managing risk",
    digitalFootprint: "the trail of information created by a person's digital activities",
    data: "recorded information that can be organized and analyzed",
    harassment: "unwanted conduct that intimidates, humiliates or threatens a person",
    intellectualProperty: "legal interests protecting certain creative works, inventions and distinctive signs"
  };
  var names = { dueProcess: "due process", publicInterest: "public interest", conflictOfInterest: "conflict of interest", digitalFootprint: "digital footprint", intellectualProperty: "intellectual property" };
  // [title, five concepts, explanatory note, classroom scenario, applied response]
  var lessons = [
    // Grade 7: belonging and everyday citizenship
    ["Citizenship in everyday life", "civics community citizenship responsibility respect", "Civics connects public institutions with daily conduct. A learner can contribute to a community before becoming eligible to vote. Rights and responsibilities should be discussed together, without treating rights as rewards for good behavior.", "A learner says only adults can help the school community. Another proposes sharing books and keeping a common reading area tidy.", "The second proposal is a form of age-appropriate civic participation. Learners can agree fair borrowing rules, share responsibilities and check whether everyone can use the books."],
    ["Rules and fair decisions", "rule fairness cooperation inclusion discrimination", "Good classroom rules have a clear purpose and can be explained. Fairness may require different support for different needs. A popular decision can still be unfair if it excludes a vulnerable learner.", "A class votes to place its shared noticeboard where a learner with limited mobility cannot reach it.", "Ask who is excluded, move the noticeboard to an accessible place and consult the affected learner. Majority support does not remove the need for fair access."],
    ["Identity, diversity and dignity", "identity diversity dignity stereotype dialogue", "People have several identities, including family, language and community connections. No single group description explains every person. Respectful questions and listening are better ways to learn than stereotypes.", "A group assigns a role to a new pupil based only on the language spoken at home.", "Ask the pupil about interests and skills rather than assuming them. Allocate roles fairly and allow learners to choose or rotate responsibilities."],
    ["National symbols and shared belonging", "symbol heritage unity patriotism respect", "Liberia's flag is one symbol of national identity. Symbols can invite reflection on shared history and responsibilities. Caring for one's country includes protecting people's dignity and improving public life, not hostility toward other countries.", "Learners plan a display about Liberia but want to mock another country's flag beside it.", "Celebrate Liberia through accurate explanations and respectful artwork. Remove the mockery because national pride does not require disrespect toward other people."],
    ["Resolving disagreements peacefully", "conflict mediation compromise empathy violence", "Conflict is not the same as violence. People can disagree without threats or harm. For ordinary disagreements, calm listening and voluntary mediation can help; threats or abuse should be reported to a trusted responsible adult rather than handled alone.", "Two clubs want the same classroom after school. Their members begin insulting one another.", "Pause the insults, ask each group about its needs and negotiate a timetable. A neutral teacher can help mediate; any threat of harm needs adult attention."],
    ["A community service project", "service volunteering sanitation resource responsibility", "A useful service project begins by identifying a real need. Learners should ask permission, share manageable tasks and avoid dangerous work. A simple review helps a group learn what improved and what needs attention.", "A class wants to clean its surroundings but finds broken glass and an open drain.", "Do not ask children to handle sharp waste or enter the drain. Inform a responsible adult, choose safe tasks and arrange appropriate trained support for hazardous work."],
    // Grade 8: institutions and public decisions
    ["Why communities need government", "government law authority accountability publicInterest", "Government organizes public decisions and services. Public power should have defined limits and be used for public purposes. Accountability means people in authority should explain how decisions are made and resources used.", "A school committee collects money for repairs but refuses to explain how it was spent.", "Request a clear record of income, expenditure and remaining funds through the school's agreed procedures. Asking for an account is about responsible management, not making an unsupported accusation."],
    ["Three branches of government", "legislature executive judiciary separation oversight", "Liberia's constitutional framework distinguishes the legislative, executive and judicial branches. The legislature makes laws, the executive administers them and the judiciary interprets law in disputes. Their separate functions and checks help limit concentrated power.", "In a classroom simulation, one pupil writes every rule, enforces it and decides every complaint without review.", "Distribute the functions among different groups and provide a review process. Explain that real constitutional powers are more complex than the simulation and must be checked against the Constitution."],
    ["County and community administration", "county district decentralization consultation representation", "Local issues often require communication between residents and public offices. A county and a district are not interchangeable terms. Before presenting a request, find out which institution has responsibility and how residents can contact it safely.", "Residents want a damaged footpath repaired but send a request to an office that does not manage it.", "Identify the responsible authority, describe the location and problem, consult affected residents and submit the request through an appropriate channel. Keep a copy and seek a response."],
    ["Elections and responsible choice", "democracy election ballot manifesto participation", "An election needs clear procedures, informed choice and fair treatment. Candidates' promises should be examined for practicality, not accepted because of gifts or rumors. Classroom elections can model respectful campaigning without asking learners to disclose real political affiliations.", "In a class election, a candidate promises gifts to anyone who shows proof of voting for them.", "Reject vote-buying and protect voters' private choices. Compare policies, explain the agreed rules and report pressure to the teacher overseeing the simulation."],
    ["Rights and responsibilities", "rights liberty equality privacy remedy", "Rights protect people against unjust treatment. Exercising a freedom does not justify harming others or ignoring their rights. When a right may have been violated, learners should use safe reporting routes and seek appropriate advice rather than retaliation.", "A learner shares another pupil's private message with the class and says freedom of expression allows anything.", "Explain that freedom of expression does not erase others' privacy or dignity. Stop further sharing, seek adult support and discuss an appropriate remedy without publicly repeating the private information."],
    ["Public money and shared priorities", "tax budget revenue expenditure priority", "Public money should be planned and accounted for. A budget compares available revenue with proposed expenditure. Limited resources require choices that should be explained using needs, likely benefits and fair procedures.", "A mock community has 1,000 units to spend. A safe water repair costs 700 and a celebration costs 600.", "Both cannot be funded in full from 1,000 units. Compare urgency and benefits, prioritize the essential repair if justified and adjust or defer the celebration. Show the arithmetic and remaining balance."],
    // Grade 9: civic skills and safe participation
    ["Evidence and responsible media use", "evidence source verification misinformation opinion", "A message's popularity does not establish its truth. Readers should check who produced it, when it was made and what evidence supports it. A factual claim should be distinguished from a value judgment or personal preference.", "A forwarded message announces that a school is closed but gives no date or official contact.", "Check a trusted school communication channel or responsible school officer before forwarding. Explain that an undated, unattributed message is not enough evidence of a closure."],
    ["Child safety and respectful schools", "consent safety bullying dignity remedy", "A safe school protects learners from intimidation and exploitation. Consent must be freely given and cannot justify abuse or override child-protection requirements. Learners should know trusted reporting routes and should not investigate dangerous incidents themselves.", "A group threatens to share embarrassing images unless a pupil does its homework.", "Do not comply with or circulate the threat. Preserve relevant evidence safely, seek help from a trusted adult and follow safeguarding procedures. Protect the affected pupil's privacy."],
    ["Disability inclusion and access", "accessibility inclusion equality consultation advocacy", "Equal participation requires attention to barriers, not assumptions about ability. Accessible information, routes and activities benefit different learners. Consult affected people respectfully and avoid treating them as helpless or speaking for them without permission.", "A school meeting uses only spoken announcements, so a pupil with a hearing difficulty misses the instructions.", "Provide written or otherwise accessible instructions and ask what communication support is useful. Include the pupil in planning rather than assuming one solution suits everyone."],
    ["Honesty and everyday integrity", "integrity corruption bribery accountability transparency", "Integrity means acting fairly even when no one is watching. An improper payment can distort a decision and disadvantage others. Suspected wrongdoing should be reported with evidence through safe channels, without reckless public allegations.", "A club treasurer asks for a private payment before allowing a member to inspect the club's agreed accounts.", "Reject the improper condition, refer to the club's access rules and report the concern to an appropriate responsible adult. Keep an accurate account of what occurred without spreading rumors."],
    ["Environmental citizenship", "environment conservation pollution sustainability prevention", "Environmental problems connect individual actions with collective decisions. Reducing waste and protecting water require cooperation and safe practices. A project should consider who benefits, who may be harmed and how improvements can continue.", "A cleanup group proposes burning plastic beside classrooms because it removes visible litter quickly.", "Do not burn plastic near people. Seek locally appropriate safe collection and disposal arrangements, reduce avoidable waste and discuss health risks with responsible adults."],
    ["Petitions and constructive advocacy", "advocacy petition evidence consultation dialogue", "Constructive advocacy identifies a specific problem and a realistic request. Evidence and respectful language help decision-makers understand the issue. Participation should be voluntary, and personal details should not be collected without a clear need and proper protection.", "Learners want more reading time and plan to publish a petition containing every pupil's address.", "Collect only necessary information with appropriate permission. Present evidence about reading needs, suggest a workable timetable and submit the request respectfully without exposing home addresses."],
    // Grade 10: constitutional literacy
    ["Constitutional government in Liberia", "constitution sovereignty legitimacy law authority", "A constitution establishes a framework for public power and protected rights. Liberia's current constitutional framework dates from 1986. Studying a constitutional issue means reading the relevant text carefully and distinguishing it from ordinary rules or personal opinions.", "A student claims a school club's new rule automatically changes the national Constitution.", "Distinguish a club rule from constitutional law. A club cannot amend the Constitution; use the constitutional text and recognized legal procedures when investigating national constitutional change."],
    ["Rule of law and due process", "law dueProcess presumption impartiality appeal", "The rule of law requires public power to operate through law rather than arbitrary preference. Fair procedures include opportunities to understand and respond to allegations as required by applicable rules. Being accused is not itself proof of guilt.", "A committee punishes a member based on an anonymous accusation without hearing their response.", "Do not treat accusation as proof. Use fair authorized procedures, examine reliable evidence, allow an appropriate response and provide an available review route. Serious legal matters require qualified advice."],
    ["Constitutional rights in practice", "rights equality liberty privacy dignity", "Rights can come into tension in practical situations. A careful response identifies whose interests are affected and what lawful limits apply. A classroom discussion is not a substitute for legal advice about a real dispute.", "A debate team wants to publish an unverified accusation about a named pupil as an exercise in free expression.", "Use an anonymized fictional scenario instead. Distinguish criticism of ideas from unsupported personal accusations and protect privacy, reputation and dignity."],
    ["Checks, balances and public oversight", "separation oversight legislature executive judiciary", "Checks and balances distribute power and create opportunities for lawful review. Institutional independence is not permission to ignore legal duties. Analysis should ask who has authority, which procedure applies and what safeguards protect fair decisions.", "A mock executive group says no other institution may ask how it implemented an agreed public program.", "Explain the role of lawful oversight and require an account through the simulation's agreed rules. Distinguish checking implementation from improperly taking over another institution's function."],
    ["Constitutional change and public debate", "amendment referendum participation evidence dialogue", "Constitutional change follows the procedures established by the Constitution. Public debate should clarify the existing rule, proposed change and likely effects. A petition or popular message is not itself proof that a constitutional amendment has taken legal effect.", "A social-media post says a constitutional rule changed because many users supported a poll.", "Check official legal records and the constitutional amendment procedure. Explain why an informal online poll cannot substitute for the required legal process."],
    ["Justice and reconciliation", "justice reconciliation testimony empathy restitution", "Reconciliation seeks safer relationships without denying harm. Justice, acknowledgment and appropriate remedies may support that process. Classroom work on Liberia's conflict and peace should use sensitive published material, never pressure learners to disclose traumatic experiences.", "A class plans a peace activity and asks every learner to describe personal family experiences of violence.", "Make participation safe and voluntary, use fictional or published examples and do not demand personal disclosures. Emphasize dignity, support and respectful discussion rather than forced forgiveness."],
    // Grade 11: public ethics and development
    ["Transparent public service", "publicInterest accountability transparency integrity service", "Public service should respond to public needs through fair procedures. Transparent criteria make decisions easier to understand and review. Openness must still respect lawful confidentiality and personal privacy.", "A scholarship committee publishes awards but not the selection criteria, leaving applicants uncertain about fairness.", "Request clear eligibility and assessment criteria plus a lawful review route. Publish useful aggregate information while protecting applicants' private data."],
    ["Procurement and conflicts of interest", "procurement conflictOfInterest bribery audit oversight", "Procurement should seek appropriate value and follow applicable rules. A conflict of interest can exist even before proven wrongdoing. Disclosure, recusal where required and independent review help protect trust and fair competition.", "A committee member recommends buying all supplies from a business owned by a close relative and does not disclose the connection.", "Disclose the relationship and follow conflict-of-interest procedures, including stepping aside when required. Compare eligible bids fairly and keep records rather than assuming the cheapest or related supplier must win."],
    ["Reading budgets and public accounts", "budget revenue expenditure audit priority", "A budget is a plan; accounts record what actually happened. Differences may have legitimate explanations or may require investigation. Compare dates, categories and evidence before drawing conclusions about spending.", "A project planned to spend 500 units on materials but accounts show 650 after prices rose. A learner immediately calls the difference theft.", "Calculate the 150-unit difference and seek invoices, approvals and explanations. A variance merits review but does not by itself prove theft."],
    ["Policy choices and evaluation", "policy stakeholder indicator evaluation evidence", "A policy should state the problem, proposed action and intended results. Indicators help distinguish activity from improvement. Good evaluation considers unintended effects and asks whether changes can reasonably be attributed to the intervention.", "A reading program reports the number of books distributed as proof that every pupil's reading improved.", "Book distribution is an activity measure, not direct evidence of reading gains. Add suitable before-and-after reading measures, participation information and consideration of other influences."],
    ["Citizenship and inclusive development", "development inequality entrepreneurship accessibility sustainability", "Development involves opportunities and capabilities, not only higher money totals. A useful initiative should ask who can participate and who may be excluded. Enterprises can serve community needs while remaining accountable for environmental and social effects.", "A proposed market charges fees that small sellers cannot afford and has steps but no accessible entrance.", "Consult different sellers and customers, assess affordability and access barriers, and compare feasible design and fee alternatives. Explain both financial sustainability and inclusion."],
    ["Disaster readiness and civic responsibility", "resilience prevention cooperation safety resource", "Preparedness identifies risks before emergencies occur. Trusted guidance, safe routes and accessible communication help protect people. Learners should take age-appropriate roles rather than attempt rescues or handle dangerous materials.", "Heavy rain cuts a usual route to school. A group proposes crossing fast-moving water together to avoid being late.", "Do not enter floodwater. Move to a safe place, contact responsible adults and follow trusted emergency guidance. Review a safer communication and route plan afterward."],
    // Grade 12: national and international civic reasoning
    ["Liberia and international cooperation", "diplomacy treaty multilateralism sovereignty interdependence", "States cooperate on problems that cross borders while pursuing public interests. Liberia participates in regional and international institutions, including ECOWAS, the African Union and the United Nations. Membership does not mean every institution has identical powers or functions.", "A learner says one international organization controls every public decision in all member countries.", "Compare the organization's agreed mandate with states' responsibilities. Explain that cooperation operates through specific rules and commitments, not a single unlimited global government."],
    ["Regional peace and collective action", "peacebuilding diplomacy dialogue justice cooperation", "Peacebuilding addresses causes of conflict as well as immediate violence. Regional cooperation can support communication, institutions and recovery. Claims about a specific mission or agreement should be checked against reliable records rather than generalized from another case.", "A discussion group proposes that peace means only stopping visible fighting, with no attention to exclusion or distrust.", "Explain that lasting peace also needs credible institutions, dialogue, fair opportunities and appropriate justice. Identify feasible measures without claiming a single activity guarantees peace."],
    ["Migration, displacement and human dignity", "migration refugee asylum displacement humanitarian", "People move for different and sometimes overlapping reasons. Refugee and asylum categories have legal meanings; not every migrant has the same status. Whatever their status, people should be treated with dignity, and real protection questions require competent advice.", "A rumor labels every new arrival a criminal and asks pupils to publish newcomers' names and locations.", "Reject collective blame and protect personal information. Check claims responsibly, welcome safe inclusive participation and refer specific protection needs to appropriate trusted services."],
    ["Economic interdependence and citizenship", "trade interdependence development inequality tax", "Trade connects producers and consumers across borders. Benefits and costs may be distributed unevenly, so civic analysis asks who gains, who bears risks and what fair safeguards are possible. An economic claim should distinguish evidence from a preferred policy position.", "A new imported product lowers prices for buyers but local producers report lost income.", "Compare consumer benefits with producer impacts using evidence. Discuss feasible responses such as skills support, fair competition and adjustment measures without assuming all trade is either harmful or beneficial."],
    ["Digital citizenship and public debate", "digitalFootprint privacy consent verification intellectualProperty", "Digital participation leaves records that can travel beyond the intended audience. Responsible sharing involves checking claims, protecting personal information and respecting creators' rights. A public-interest purpose does not automatically justify exposing private details.", "A civic club copies a photographer's image without permission and posts volunteers' phone numbers to promote an event.", "Use an appropriately licensed or permitted image with required credit. Obtain suitable permission for necessary contact information or publish an official contact instead; avoid exposing volunteers' private numbers."],
    ["Civic inquiry and an action proposal", "evidence consultation policy indicator accountability", "A civic inquiry turns a broad concern into an answerable question. A sound proposal states evidence, affected groups, feasible actions, responsibilities and review measures. Ethical inquiry protects participants and clearly reports uncertainties.", "A final-year group wants to improve access to school drinking water but begins with a demand for an expensive system without studying the problem.", "Map the current access problem safely, consult relevant users and staff, compare feasible options and estimate costs. Propose responsible roles, a realistic timetable and indicators for access and maintenance, with teacher approval before any action."]
  ];
  var periods = ["I", "II", "III", "IV", "V", "VI"];
  root.CI_CURRICULUM = lessons.map(function (v, index) {
    var grade = 7 + Math.floor(index / 6), period = periods[index % 6];
    var keys = v[1].split(" ");
    var terms = keys.map(function (key) { var term = names[key] || key; return { t: term, d: glossary[key], x: "In civics, " + term + " means " + glossary[key] + "." }; });
    var title = v[0], facts = terms.map(function (term) { return { q: "What is meant by “" + term.t + "”?", a: term.d + "." }; });
    facts.push({ q: "What civic issue is raised in this unit's classroom scenario?", a: v[3] }, { q: "Explain a responsible response to the scenario and give reasons.", a: v[4] });
    return {
      grade: grade, period: period, sem: index % 6 < 3 ? "One" : "Two", title: title,
      subtitle: "Civics · Original supplementary material — teacher review required",
      source: { type: "original", note: "Original teaching resource; not an official curriculum transcription or official examination material." },
      objectives: ["Explain the five key concepts in " + title.toLowerCase() + ".", "Identify the people and interests affected by a civic decision.", "Apply the unit's ideas to a fictional classroom scenario.", "Justify a safe, fair and evidence-based response."],
      outcomes: ["Use civic vocabulary accurately.", "Explain a decision using reasons and relevant evidence.", "Listen respectfully to alternative views."],
      note: v[2], terms: terms, facts: facts,
      study: [{ k: "h3", t: "Understanding " + title }, { k: "p", t: v[2] },
        { k: "h3", t: "Key concepts" }, { k: "bul", items: terms.map(function (term) { return "**" + term.t + "** — " + term.d + "."; }) },
        { k: "h3", t: "A fictional classroom example" }, { k: "p", t: v[3] },
        { k: "h3", t: "Worked civic reasoning" }, { k: "p", t: v[4] },
        { k: "h3", t: "Check your reasoning" }, { k: "p", t: "Identify the issue, distinguish verified facts from assumptions, consider whose rights and needs are affected, compare safe options, and explain your choice. Do not assume majority support alone proves a decision fair." },
        { k: "p", t: "This is original supplementary teaching material. Review against the school's approved scheme of work; real legal and safeguarding concerns should be referred to qualified responsible people." }],
      tf: [
        { s: "In this unit, " + terms[0].t + " means " + terms[0].d + ".", a: "True", why: "This is the working definition used in the unit." },
        { s: "In this unit, " + terms[1].t + " means " + terms[2].d + ".", a: "False", why: terms[1].t + " means " + terms[1].d + "; the statement describes " + terms[2].t + "." },
        { s: "In this unit, " + terms[3].t + " means " + terms[3].d + ".", a: "True", why: "The definition helps distinguish this concept from the other terms." },
        { s: "A civic claim becomes reliable simply because many people repeat it.", a: "False", why: "Popularity is not a substitute for relevant evidence and verification." },
        { s: "A reasoned civic decision should consider people who may be affected.", a: "True", why: "Considering different interests and rights helps identify unfair or unsafe consequences." }
      ],
      casestudy: { title: title + " — a decision to discuss", text: v[3], questions: [
        { q: "What is the main problem and who may be affected?", a: "Identify the people named in the scenario and the unfair, unsafe or unsupported action described. " + v[3] },
        { q: "What response would you recommend, and why?", a: v[4] },
        { q: "Which two key concepts help explain your recommendation?", a: "Accept two accurately applied concepts from: " + terms.map(function (term) { return term.t; }).join(", ") + ". Require an explanation linking each to the scenario." }
      ] },
      apply: [
        { q: "Apply this unit's ideas to the following scenario: " + v[3] + " What should happen next?", a: v[4] },
        { q: "Give an example of a fair school decision connected with “" + title + "”. Explain which interests and evidence you would consider.", a: "Accept a relevant fictional school example. Require accurate use of a unit concept, identification of affected people, a safe response and a reason supported by relevant information." }
      ],
      debate: [{ q: "Discuss: A civic decision should be judged by its fairness and evidence, not only by its popularity. Use examples from “" + title + "”.", a: "A strong response states a position, accurately explains at least two unit concepts, uses a relevant example, addresses another viewpoint and reaches a reasoned conclusion. Do not award marks for a particular party preference." }],
      mapwork: { title: "A civic decision-making flowchart", caption: "Draw a flowchart showing how to analyze this unit's scenario safely.", items: [
        { p: "Identify", f: "State the issue and affected people" }, { p: "Check", f: "Separate evidence from assumptions" }, { p: "Compare", f: "Consider fair and safe options" }, { p: "Decide", f: "Explain a feasible response" }, { p: "Review", f: "Check the outcome and revise if needed" }
      ] },
      project: { title: "A civic learning poster: " + title, brief: "Use only fictional examples or teacher-approved published information. Do not collect private political opinions or sensitive personal experiences.",
        steps: ["Explain two unit concepts in your own words.", "Describe the classroom scenario and identify affected people.", "Compare two possible responses and explain a safe, fair recommendation.", "Present the poster and respond respectfully to questions."],
        criteria: ["Accurate concepts", "Relevant reasoning", "Attention to safety and inclusion", "Clear communication"] },
      activities: ["Discuss the fictional scenario in pairs.", "Match key terms with meanings and explain the differences.", "Role-play a respectful decision-making discussion without using real political affiliations."],
      materials: ["Chalkboard or reusable paper", "Teacher-reviewed copies of this unit", "For constitutional topics: a teacher-verified copy of Liberia's Constitution"],
      assessment: ["Five-term vocabulary check", "Scenario response with reasons", "Poster assessed for accuracy, fairness and evidence"]
    };
  });
})(window);
