/* Curriculum data — Republic of Liberia, PHONICS & WORD STUDY, Grades 1–12.
   6 periods per grade, 72 units. The Phonics course is the decoding strand of
   the national curriculum, organised as one continuous course from Grade 1 to
   Grade 12:

     · Grades 1–6  — the phonics strand of the "English 1-6" guide
     · Grades 7–9  — the word-study strand of the "English 7-9" guide
     · Grades 10–12— the word-building strand of the "English Grammar 10-12" guide

   Every unit below names its source period (src: "en:1:I" or "eg:10:I"), and
   takes THAT official unit's pattern list (`phonics[]`), vocabulary (`words[]`)
   and sight words (`sight[]`) — so no patterns or word lists are invented.
   The unit title, note, focus list and study text are the focused phonics
   teaching text for the period.

   Same unit shape used by the shared renderer and the GEN_PHO engine:
     grade · period · sem · icon · title · subtitle · outcomes[] · objectives[]
     · note · focus[]
     · phonics[]{p,label,words}   the sounds / patterns / word parts
     · words[]{w,s,d,x}           vocabulary: word, syllables/"say" hint,
                                  definition, example sentence
     · sight[]                    words to know on sight
     · study[]                    block list rendered verbatim
     · activities[] · materials[] · assessment[]

   Per the project rule the digital research links listed in the source guides
   are deliberately omitted: the pack must stay fully offline.

   LOAD ORDER: PHO_CURRICULUM is built at load time from EN_CURRICULUM and
   EG_CURRICULUM, so this file must be concatenated AFTER data-en.js and
   data-eg.js (build.sh keeps it after data-eg.js).
*/

var PHO_UNITS = [
  /* ================================ GRADE 1 ================================ */
  { g:1, p:"I", sem:"One", icon:"🔤", src:"en:1:I",
    title:"The Alphabet, Letter Sounds and First Words",
    sub:"Letter names and sounds, VC words, and the -at, -ig and -un families",
    note:"This period teaches the **names and sounds of the 26 letters**, the two families of letters, and the first words we can read: VC words such as **at, in, up** and CVC words such as **cat, pig, bus**.",
    focus:["Letter names and sounds","Vowels and consonants","VC and CVC words","The -at, -ig and -un families","Blending and segmenting"],
    intro:"The English alphabet has **26 letters**, and every letter has a **name** and a **sound**. The letters fall into two families: the **vowels** — a, e, i, o, u (and sometimes y) — and the **21 consonants**. In this period we read and spell our first words. A **VC word** is a vowel followed by a consonant, such as at, in, up; a **CVC word** is a consonant, a vowel and a consonant, such as cat, pig, bus. We **blend** the sounds from left to right to read — /c/ – /a/ – /t/ makes cat — and **segment** the word back into its sounds to spell it." },
  { g:1, p:"II", sem:"One", icon:"🧩", src:"en:1:II",
    title:"Consonant Blends: bl, cl, fl and gl",
    sub:"Two consonants that keep their own sounds at the start of a word",
    note:"A **blend** is two consonants side by side, each keeping its own sound: /b/ + /l/ in black, /c/ + /l/ in clock, /f/ + /l/ in flag, /g/ + /l/ in glass.",
    focus:["Beginning l-blends","bl, cl, fl and gl","Blending two consonant sounds","Reading and spelling blend words"],
    intro:"A **consonant blend** is two or more consonants written together, and each one keeps its own sound. At the beginning of a word, **bl** says /bl/ as in black, **cl** says /cl/ as in clock, **fl** says /fl/ as in flag and **gl** says /gl/ as in glass. Read a blend word by saying every sound, not by guessing: /b/ – /l/ – /a/ – /ck/ makes black." },
  { g:1, p:"III", sem:"One", icon:"🎯", src:"en:1:III",
    title:"More Word Families: -ain, -and and -elp",
    sub:"Changing the first sound to build families of rhyming words",
    note:"A **word family** shares the same ending: rain, main, pain; hand, sand, land; help, yelp.",
    focus:["Word families and rimes","-ain, -and and -elp","Rhyming words","Building new words from families"],
    intro:"A **word family** (or rime) is the ending a group of words shares. Change only the first sound and you can read many new words: **-ain** — rain, main, pain, train; **-and** — hand, sand, land, stand; **-elp** — help, yelp. Because the ending stays the same, the word family helps us read and spell whole sets of words at once." },
  { g:1, p:"IV", sem:"Two", icon:"💡", src:"en:1:IV",
    title:"Magic e: a_e, i_e and o_e",
    sub:"The silent e that makes the vowel say its name",
    note:"In **magic e** words the final **e** is silent, and it makes the vowel say its own name: cap → cape, kit → kite, not → note.",
    focus:["The silent e rule","a_e, i_e and o_e","Long vowel sounds","Magic e word pairs"],
    intro:"**Magic e** is a final silent **e** that makes the vowel before it say its own name: the vowel becomes **long**. Compare cap with cape, kit with kite, not with note — without e the vowel is short, with e it is long. When you read a magic-e word, look for the pattern vowel–consonant–e, say the long vowel, then finish the word." },
  { g:1, p:"V", sem:"Two", icon:"🔍", src:"en:1:V",
    title:"Word Families with -all, -ound and -ong",
    sub:"Reading and spelling the -all, -ound and -ong families",
    note:"The **-all**, **-ound** and **-ong** families: ball, call, tall; sound, round, found; song, long, strong.",
    focus:["The -all family","The -ound family","The -ong family","Rhyme and spelling"],
    intro:"These families end with a clear vowel sound that stays the same: **-all** — ball, call, tall, small; **-ound** — sound, round, found, ground; **-ong** — song, long, strong. Say the family ending first, then add the beginning sound, and check the spelling of the ending every time." },
  { g:1, p:"VI", sem:"Two", icon:"🔊", src:"en:1:VI",
    title:"Digraphs: sh, ch and th",
    sub:"Two letters that make one new sound together",
    note:"A **digraph** is two letters that stand for one sound: **sh** as in ship, **ch** as in chair, **th** as in this and thin.",
    focus:["The sh digraph","The ch digraph","The th digraph (two sounds)","Digraph at the start and end of words"],
    intro:"A **digraph** is two letters that together make ONE new sound. **sh** says /sh/ as in ship and fish; **ch** says /ch/ as in chair and lunch; **th** has two sounds — the soft /th/ in thin and the voiced /th/ in this. Look for the two letters together, say the single sound, then finish the word." },

  /* ================================ GRADE 2 ================================ */
  { g:2, p:"I", sem:"One", icon:"📖", src:"en:2:I",
    title:"The oo Sound, -er and the -tion Ending",
    sub:"Vowel teams, the -er ending and words that end in -tion",
    note:"**oo** can say /oo/ as in moon or the shorter /oo/ as in book; **-er** names a person or thing that does something; **-tion** ends many long nouns.",
    focus:["The oo sound","The -er ending","Words ending in -tion","Reading longer words"],
    intro:"**oo** is a vowel team: in moon, food and school it says /oo/; in book, look and good it says the shorter /oo/ sound. The ending **-er** makes words such as teacher, farmer and baker. Many longer nouns end in **-tion** — station, action, question. Read long words in parts: sta-tion, ac-tion." },
  { g:2, p:"II", sem:"One", icon:"🧱", src:"en:2:II",
    title:"Digraphs Review: sh, ch, th and wh",
    sub:"The four consonant digraphs in words and sentences",
    note:"**sh**, **ch**, **th** and **wh** are each one sound made by two letters: ship, chair, thin, when.",
    focus:["sh, ch, th and wh","Digraph at the start and end","Reading and spelling with digraphs"],
    intro:"Review the four consonant digraphs: **sh** (ship, wash), **ch** (chair, lunch), **th** (thin, this, bath) and **wh** (when, white, wheel). Each pair of letters stands for one sound, so look for the pair first, then read the word." },
  { g:2, p:"III", sem:"One", icon:"⏱️", src:"en:2:III",
    title:"Endings -ed and -ing and Silent Letters",
    sub:"Adding endings to verbs, and letters we do not say",
    note:"**-ed** and **-ing** are added to verbs to change the time of the action; **silent letters** are written but not sounded, like the k in knee.",
    focus:["-ed and -ing endings","Adding endings to base words","Silent letters","Spelling when endings are added"],
    intro:"We add **-ed** to a verb to show the past — jump → jumped — and **-ing** to show action going on — jump → jumping. Some words have **silent letters**, letters that are written but not sounded: the k in knee, the b in lamb, the w in write. When you add an ending, keep the base word, then add the ending." },
  { g:2, p:"IV", sem:"Two", icon:"🗣️", src:"en:2:IV",
    title:"Suffixes -ful and -y and the ow Sound",
    sub:"Endings that make adjectives and the two sounds of ow",
    note:"**-ful** means full of (careful), **-y** makes an adjective (rainy), and **ow** can say /ow/ as in cow or the long /o/ of snow.",
    focus:["The suffix -ful","The -y ending","The two sounds of ow","Adjectives from nouns"],
    intro:"A **suffix** is an ending added to a base word. **-ful** means full of: care → careful, help → helpful. **-y** makes adjectives: rain → rainy, sun → sunny. The letters **ow** make two sounds: /ow/ as in cow and down, and the long /o/ as in snow and grow. Read the word, listen for the sound, then check the spelling." },
  { g:2, p:"V", sem:"Two", icon:"🧐", src:"en:2:V",
    title:"The ea Vowel Team and the Endings -ous and -ent",
    sub:"Vowel teams and word endings in longer words",
    note:"**ea** says /ee/ in eat, /e/ in bread and /ay/ in great; **-ous** (famous) and **-ent** (present) are common word endings.",
    focus:["The ea vowel team","The -ous ending","The -ent ending","Endings in longer words"],
    intro:"The vowel team **ea** has more than one sound: /ee/ in eat and mean, /e/ in bread and head, and even /ay/ in great. The endings **-ous** (famous, dangerous) and **-ent** (present, different) are common in longer words. Read the word in parts, and learn the sound of each ending." },
  { g:2, p:"VI", sem:"Two", icon:"📝", src:"en:2:VI",
    title:"Endings -age and -ture and Double Letters",
    sub:"Word endings that sound like /ij/ and /cher/, and doubled consonants",
    note:"**-age** (village, message), **-ture** (nature, picture) and **double letters** (bubble, happy) are the spelling patterns of this period.",
    focus:["The -age ending","The -ture ending","Double letters","Spelling long words"],
    intro:"The endings **-age** (village, message, cabbage) and **-ture** (nature, picture, creature) sound differently from the way they look, so learn them as whole endings. **Double letters** — bubble, happy, letter — usually show a short vowel just before them. Look for the pattern before the ending, then say the whole word." },

  /* ================================ GRADE 3 ================================ */
  { g:3, p:"I", sem:"One", icon:"✒️", src:"en:3:I",
    title:"Long a Spellings, -tion and the ph Digraph",
    sub:"The ways to spell long a, the -tion ending and ph = /f/",
    note:"Long **a** can be spelled **-ain** (rain) or **-ane** (cane); **-tion** ends many nouns; **ph** says /f/ as in phone.",
    focus:["Long a spellings -ain and -ane","The -tion ending","ph says /f/","Choosing the right spelling"],
    intro:"Long /a/ has more than one spelling: **-ain** — rain, train, plain; **-ane** — cane, plane, lane. The ending **-tion** (station, action) is a very common noun ending. The digraph **ph** says /f/, as in phone, photo and elephant." },
  { g:3, p:"II", sem:"One", icon:"🏷️", src:"en:3:II",
    title:"The shun Endings, -ence/-ance and -ate",
    sub:"Common noun and verb endings in longer words",
    note:"The **shun** sound is spelled **-tion** or **-sion** (station, vision); **-ence** / **-ance** end nouns; **-ate** ends many verbs.",
    focus:["-tion and -sion (shun)","-ence and -ance","The -ate ending","Spelling noun and verb endings"],
    intro:"The sound /shun/ at the end of a word is spelled **-tion** (station, action, nation) or **-sion** (vision, decision). Nouns often end in **-ence** (difference) or **-ance** (distance), and many verbs end in **-ate** (celebrate, separate). Say the whole word, then write the ending you hear." },
  { g:3, p:"III", sem:"One", icon:"🤝", src:"en:3:III",
    title:"Comparing Endings -er/-est and the Suffixes -ous and -ive",
    sub:"Adjectives that compare and adjectives made from other words",
    note:"**-er** and **-est** compare (taller, tallest); **-ous** means full of (famous); **-ive** makes adjectives (active).",
    focus:["-er and -est comparisons","The -ous suffix","The -ive suffix","Adjectives and their endings"],
    intro:"Add **-er** to compare two things — tall → taller — and **-est** for more than two — tall → tallest. The suffix **-ous** means full of: fame → famous, danger → dangerous. **-ive** makes adjectives: act → active, create → creative." },
  { g:3, p:"IV", sem:"Two", icon:"💌", src:"en:3:IV",
    title:"Verb Endings -s/-es, the -le Ending and the Root -ject",
    sub:"How verbs change with he/she/it, and words ending in -le",
    note:"**-s** or **-es** is added to verbs for he, she and it; **-le** ends many words (table, little); **-ject** means throw (reject, inject).",
    focus:["-s and -es verb endings","The -le ending","The root -ject","Root meaning: throw"],
    intro:"For he, she and it we add **-s** or **-es** to a verb: I jump, she jumps; I wash, she washes. Many words end in **-le** (table, little, apple). The root **-ject** means throw: reject (throw back), inject (throw in), project (throw forward)." },
  { g:3, p:"V", sem:"Two", icon:"🌱", src:"en:3:V",
    title:"The -ing Ending, Person Endings -er/-or and Soft g",
    sub:"Action words, people who do things, and g that says /j/",
    note:"**-ing** shows action going on; **-er** / **-or** name a person (teacher, actor); **soft g** says /j/ before e, i or y (gem, giant).",
    focus:["The -ing ending","-er and -or for people","Soft g before e, i and y","Spelling changes with -ing"],
    intro:"**-ing** shows action going on: read → reading, run → running. **-er** and **-or** name a person who does something: teach → teacher, act → actor. **g** is soft, saying /j/, before e, i or y: gem, giant, gym; before a, o and u it says /g/: game, go, gun." },
  { g:3, p:"VI", sem:"Two", icon:"🧱", src:"en:3:VI",
    title:"Prefixes un-, dis-, re- and the Suffixes -ful and -less",
    sub:"Word parts that change meaning at the front and the back",
    note:"**un-** (not), **dis-** (not / opposite) and **re-** (again) are prefixes; **-ful** (full of) and **-less** (without) are suffixes.",
    focus:["Prefixes un-, dis- and re-","Suffixes -ful and -less","Opposite and repeated actions","Building and defining new words"],
    intro:"A **prefix** goes at the front of a word and changes its meaning: **un-** means not — happy → unhappy; **dis-** means not or opposite — agree → disagree; **re-** means again — write → rewrite. A **suffix** goes at the back: **-ful** means full of — careful; **-less** means without — careless." },

  /* ================================ GRADE 4 ================================ */
  { g:4, p:"I", sem:"One", icon:"🏗️", src:"en:4:I",
    title:"Short and Long Vowels and the -ative Ending",
    sub:"The vowel sounds that carry meaning, and a common adjective ending",
    note:"**Short vowels** say /a/ in cat, /e/ in bed, /i/ in pig, /o/ in box, /u/ in bus; **long vowels** say their names (cake, bike, home); **-ative** ends adjectives.",
    focus:["Short vowel sounds","Long vowel sounds","The -ative ending","Choosing the vowel sound"],
    intro:"Vowels make two families of sounds. **Short vowels**: /a/ in cat, /e/ in bed, /i/ in pig, /o/ in box, /u/ in bus. **Long vowels** say their own names: cake, bike, home, cube. The ending **-ative** (creative, active, negative) gives us many adjectives. Sound the middle of the word carefully — the vowel decides the word." },
  { g:4, p:"II", sem:"One", icon:"⏳", src:"en:4:II",
    title:"Consonant Blends and Digraphs: sl/tr, gr/bl and ch",
    sub:"Two- and three-letter clusters at the start of words",
    note:"**sl** (sleep), **tr** (tree), **gr** (green), **bl** (blue) are blends; **ch** is a digraph saying /ch/ or /k/.",
    focus:["Blends sl, tr, gr and bl","The ch digraph (ch and k sounds)","Clusters at word beginnings","Reading and spelling clusters"],
    intro:"A **blend** keeps every sound: sl in sleep, tr in tree, gr in green, bl in blue. A **digraph** makes one new sound: ch in chair and lunch, but /k/ in school and Christmas. Say the whole cluster — /s/ – /l/ — then read the rest of the word." },
  { g:4, p:"III", sem:"One", icon:"📚", src:"en:4:III",
    title:"The -ence Ending and the Prefixes pre- and con-",
    sub:"Noun endings and prefixes of time and togetherness",
    note:"**-ence** makes nouns from other words; **pre-** means before; **con-** means with or together.",
    focus:["The -ence ending","The prefix pre- (before)","The prefix con- (with)","Word parts and meanings"],
    intro:"The ending **-ence** makes nouns: differ → difference, patient → patience. **pre-** means before: pre + view = preview, a look before the event; **con-** means with or together: con + nect = connect, join together. Cover the ending, find the base word, then read the whole word." },
  { g:4, p:"IV", sem:"Two", icon:"🧩", src:"en:4:IV",
    title:"Prefixes dis-, non- and super- with Suffixes -ment, -ity and -able",
    sub:"Word parts that build new words from roots",
    note:"**dis-** (opposite), **non-** (not) and **super-** (above, very) are prefixes; **-ment**, **-ity** and **-able** are common suffixes.",
    focus:["Prefixes dis-, non- and super-","Suffixes -ment, -ity and -able","Building words from roots","Defining built words"],
    intro:"**dis-** gives the opposite: appear → disappear; **non-** means not: stop → non-stop; **super-** means above or very: market → supermarket. The suffixes build new words: **-ment** makes nouns (enjoy → enjoyment), **-ity** makes nouns (active → activity) and **-able** makes adjectives (read → readable)." },
  { g:4, p:"V", sem:"Two", icon:"🌳", src:"en:4:V",
    title:"Greek Roots auto- and bio-, and the Endings -hood and -ment",
    sub:"Word roots from Greek with common noun endings",
    note:"**auto-** means self (autograph), **bio-** means life (biology); **-hood** (childhood) and **-ment** (payment) are noun endings.",
    focus:["Root auto- (self)","Root bio- (life)","-hood and -ment endings","Greek roots in English"],
    intro:"Many English words come from Greek roots. **auto-** means self: auto + mobile = automobile, a vehicle that moves itself. **bio-** means life: bio + logy = biology, the study of life. The endings **-hood** (childhood, brotherhood) and **-ment** (payment, movement) make nouns." },
  { g:4, p:"VI", sem:"Two", icon:"🎵", src:"en:4:VI",
    title:"Diphthongs oy/oi and ew with the Blends sl and str",
    sub:"Vowel sounds that glide and consonant clusters",
    note:"**oi** and **oy** say the same /oy/ sound (coin, boy); **ew** says /oo/ (new); **sl** and **str** are consonant clusters.",
    focus:["The oy/oi diphthong","The ew vowel team","Blends sl and str","Sound-spelling choices"],
    intro:"A **diphthong** is two vowel letters that glide into one sound. **oi** and **oy** both say /oy/: coin, boy. **ew** says /oo/ as in new, few and grew. The blends **sl** (slow, sleep) and **str** (street, strong) keep every consonant sound." },

  /* ================================ GRADE 5 ================================ */
  { g:5, p:"I", sem:"One", icon:"🧭", src:"en:5:I",
    title:"Three-Letter Blends str, spl, scr and thr with the Prefix be-",
    sub:"Clusters of three consonants and the be- prefix",
    note:"**str** (street), **spl** (splash), **scr** (scratch) and **thr** (three) are three-letter blends; **be-** (below, become) is a prefix.",
    focus:["Three-letter blends","str, spl, scr and thr","The prefix be-","Reading cluster words"],
    intro:"**Three-letter blends** keep all three sounds: str in street, spl in splash, scr in scratch, thr in three. Say the cluster smoothly, then add the rest of the word. The prefix **be-** (below, behind, become) changes the meaning of the base word." },
  { g:5, p:"II", sem:"One", icon:"🌧️", src:"en:5:II",
    title:"Diphthongs oi/oy and ou/ow with the -tion Ending",
    sub:"Gliding vowel sounds and a common noun ending",
    note:"**oi/oy** say /oy/; **ou/ow** say /ow/ (house, cow); **-tion** makes nouns (action, education).",
    focus:["The oi/oy diphthong","The ou/ow diphthong","The -tion ending","Two spellings for one sound"],
    intro:"The diphthongs **oi/oy** (coin, boy) and **ou/ow** (house, cow) each give one gliding sound with two spellings. **-tion** makes nouns from verbs: act → action, educate → education. When the same sound has two spellings, look at the word, learn it, and check the ending." },
  { g:5, p:"III", sem:"One", icon:"🎭", src:"en:5:III",
    title:"Soft c and g, the -logue Ending and -ence/-ance",
    sub:"Letters that change their sound and common noun endings",
    note:"**c** says /s/ before e, i and y; **g** says /j/ before e, i and y; **-logue** (dialogue), **-ence** and **-ance** are endings.",
    focus:["Soft c before e, i, y","Soft g before e, i, y","The -logue ending","-ence and -ance nouns"],
    intro:"**c** is soft, saying /s/, before e, i or y — centre, city, mercy — and hard, /k/, otherwise — cat, cup. **g** is soft, saying /j/, before e, i or y — gem, giant, gym — and hard, /g/, otherwise — go. **-logue** ends words such as dialogue and catalogue." },
  { g:5, p:"IV", sem:"Two", icon:"📖", src:"en:5:IV",
    title:"Adverbs in -ly, the -sion Ending and -ent/-ant",
    sub:"How adverbs are built and two more common endings",
    note:"**-ly** makes adverbs (quickly); **-sion** ends nouns (decision); **-ent** / **-ant** end adjectives and nouns.",
    focus:["The -ly adverb ending","The -sion ending","-ent and -ant endings","Building words with endings"],
    intro:"**-ly** makes adverbs from adjectives: quick → quickly, soft → softly. **-sion** is a noun ending: decide → decision, confuse → confusion. The endings **-ent** (different, silent) and **-ant** (important, brilliant) appear in adjectives and nouns." },
  { g:5, p:"V", sem:"Two", icon:"🎼", src:"en:5:V",
    title:"Hard and Soft c and g",
    sub:"Knowing when c says /s/ or /k/ and g says /j/ or /g/",
    note:"**c** says /k/ before a, o, u (cat, cot, cup) and /s/ before e, i, y (cell, city, cycle); **g** says /g/ before a, o, u and /j/ before e, i, y.",
    focus:["Hard c (cat, cup)","Soft c (city, centre)","Hard g (go, game)","Soft g (gem, giant)"],
    intro:"**c** and **g** each have a hard and a soft sound. **Hard c** says /k/ before a, o and u: cat, cot, cup. **Soft c** says /s/ before e, i and y: cell, city, cycle. **Hard g** says /g/ before a, o and u: game, go, gun. **Soft g** says /j/ before e, i and y: gem, giant, gym. The letter after c or g decides the sound." },
  { g:5, p:"VI", sem:"Two", icon:"✍️", src:"en:5:VI",
    title:"Verb Endings -ise/-ize, the -ment Ending and the Root -cise",
    sub:"Word endings and the root meaning cut",
    note:"**-ise** / **-ize** make verbs (organise); **-ment** makes nouns (enjoyment); **-cise** means cut (exercise, precise).",
    focus:["-ise and -ize verb endings","The -ment ending","Root -cise (cut)","Spelling verb endings"],
    intro:"**-ise** and **-ize** make verbs: organise, realise. **-ment** makes nouns: enjoy → enjoyment, agree → agreement. The root **-cise** means cut: con + cise = concise, cut short; pre + cise = precise, cut exactly." },

  /* ================================ GRADE 6 ================================ */
  { g:6, p:"I", sem:"One", icon:"🎓", src:"en:6:I",
    title:"Syllables, the Prefixes com-/con- and the shun Endings",
    sub:"Long words in parts, together-prefixes and /shun/ endings",
    note:"**-ple** ends many words (simple, people); **com-** / **con-** mean together; **-tion** / **-sion** say /shun/.",
    focus:["The -ple ending","Prefixes com- and con-","-tion and -sion endings","Reading long words in syllables"],
    intro:"Long words are read in **syllables**, one part at a time: sim-ple, com-pare. **com-** and **con-** mean together or with: com + bine = combine; con + struct = construct. The endings **-tion** (action) and **-sion** (decision) both say /shun/." },
  { g:6, p:"II", sem:"One", icon:"🔤", src:"en:6:II",
    title:"Review: Short and Long Vowels with the -ive Ending",
    sub:"Vowel sounds that change word meaning, and adjectives in -ive",
    note:"Review the **short vowels** (cat, bed, pig, box, bus) and **long vowels** (cake, bike, home); **-ive** makes adjectives (active, creative).",
    focus:["Short vowel review","Long vowel review","The -ive ending","Vowel sound and meaning"],
    intro:"Review both families of vowel sounds. **Short vowels**: /a/ cat, /e/ bed, /i/ pig, /o/ box, /u/ bus. **Long vowels** say their names: cake, bike, home, cube. The ending **-ive** makes adjectives: act → active, create → creative, sense → sensitive." },
  { g:6, p:"III", sem:"One", icon:"🖋️", src:"en:6:III",
    title:"Nouns in -tion, the Endings -ent/-ant and Tricky Spellings rh/th",
    sub:"Common endings and spellings that are easy to confuse",
    note:"**-tion** makes nouns; **-ent** / **-ant** end adjectives and nouns; **rh** (rhyme) and **th** (this, rhythm) are tricky spellings.",
    focus:["The -tion noun ending","-ent and -ant endings","rh and th spellings","Confusable patterns"],
    intro:"**-tion** makes nouns from verbs: imagine → imagination, protect → protection. **-ent** (silent, patient) and **-ant** (important, brilliant) are common endings. Some spellings are tricky: **rh** begins rhyme and rhythm; **th** has two sounds in this and thin." },
  { g:6, p:"IV", sem:"Two", icon:"🎤", src:"en:6:IV",
    title:"Adverbs in -ly, Adjectives in -ous and Person Nouns in -ist",
    sub:"Three useful word endings and the words they build",
    note:"**-ly** makes adverbs (calmly); **-ous** means full of (famous); **-ist** names a person (artist).",
    focus:["The -ly ending","The -ous ending","The -ist ending","Adverbs, adjectives and people"],
    intro:"**-ly** makes adverbs from adjectives: calm → calmly, sudden → suddenly. **-ous** means full of: fame → famous, danger → dangerous. **-ist** names a person: art → artist, science → scientist." },
  { g:6, p:"V", sem:"Two", icon:"🔬", src:"en:6:V",
    title:"The Root -spect, the Endings -able/-ible and Prefix re-",
    sub:"The root meaning look and two adjective endings",
    note:"**-spect** means look (inspect, respect); **-able** / **-ible** mean can be (readable, visible); **re-** means again (rebuild).",
    focus:["Root -spect (look)","-able and -ible endings","The prefix re-","Root and suffix together"],
    intro:"The root **-spect** means look: in + spect = inspect, look into; re + spect = respect, look back at. **-able** and **-ible** mean can be: read → readable, see → visible. **re-** means again: build → rebuild, write → rewrite." },
  { g:6, p:"VI", sem:"Two", icon:"🧬", src:"en:6:VI",
    title:"Endings -al, -or/-er and -age",
    sub:"Adjective endings, person endings and words that end in -age",
    note:"**-al** makes adjectives (musical); **-or** / **-er** name people (actor, teacher); **-age** (village, message) is a noun ending.",
    focus:["The -al ending","-or and -er endings","The -age ending","Word formation patterns"],
    intro:"**-al** makes adjectives: music → musical, nation → national. **-or** and **-er** name people: act → actor, teach → teacher. **-age** is a noun ending: village, message, package. Say the base word, add the ending, and check the spelling." },

  /* ================================ GRADE 7 ================================ */
  { g:7, p:"I", sem:"One", icon:"🏛️", src:"en:7:I",
    title:"Nouns and Adverbs: -ation/-ion and -ly",
    sub:"Making nouns from verbs and adverbs from adjectives",
    note:"**-ation** / **-ion** make nouns from verbs (invite → invitation, act → action); **-ly** makes adverbs (quick → quickly).",
    focus:["-ation and -ion nouns","The -ly adverb ending","Word families from verbs","Spelling when endings are added"],
    intro:"The endings **-ation** and **-ion** make nouns from verbs: invite → invitation, act → action, decide → decision. **-ly** makes adverbs from adjectives: quick → quickly, careful → carefully. When you add an ending, keep the base word and check the spelling." },
  { g:7, p:"II", sem:"One", icon:"🪞", src:"en:7:II",
    title:"Prefixes un- and re- with the Suffixes -ful and -less",
    sub:"Opposites, repetition and adjectives of quantity",
    note:"**un-** means not (unhappy), **re-** means again (rewrite), **-ful** means full of (useful), **-less** means without (useless).",
    focus:["Prefix un- (not)","Prefix re- (again)","Suffix -ful (full of)","Suffix -less (without)"],
    intro:"**un-** gives the opposite: fair → unfair, kind → unkind. **re-** means again: read → reread, build → rebuild. **-ful** means full of: use → useful; **-less** means without: use → useless. Build each word by adding the part, then say what the new word means." },
  { g:7, p:"III", sem:"One", icon:"🎨", src:"en:7:III",
    title:"Adjective Endings -ive, -ous and -able",
    sub:"Three ways English makes adjectives",
    note:"**-ive** (active), **-ous** (famous) and **-able** (readable) are common adjective endings.",
    focus:["The -ive ending","The -ous ending","The -able ending","Adjectives and their bases"],
    intro:"Adjectives are built with common endings: **-ive** — act → active, create → creative; **-ous** — fame → famous, danger → dangerous; **-able** — read → readable, enjoy → enjoyable. Find the base word, add the ending, then use the adjective in a sentence." },
  { g:7, p:"IV", sem:"Two", icon:"⏳", src:"en:7:IV",
    title:"Verb Forms -en and -ought/-aught with Adverbs in -ly",
    sub:"Past forms and irregular spellings",
    note:"**-en** makes verbs and past participles (forget → forgotten); **-ought** / **-aught** spell irregular pasts (thought, caught); **-ly** builds manner adverbs.",
    focus:["The -en verb ending","-ought and -aught pasts","Adverbs of manner in -ly","Irregular forms"],
    intro:"**-en** appears in verbs and participles: forgot → forgotten, take → taken. The irregular pasts **-ought** (thought, bought) and **-aught** (caught, taught) must be learned one by one. **-ly** makes adverbs of manner: slow → slowly, soft → softly." },
  { g:7, p:"V", sem:"Two", icon:"⚖️", src:"en:7:V",
    title:"Comparison Endings -er/-est and Prefixes pre-/inter-",
    sub:"Comparing adjectives and prefixes of position and time",
    note:"**-er** compares two (taller); **-est** compares more than two (tallest); **pre-** means before, **inter-** means between.",
    focus:["-er and -est comparisons","Prefix pre- (before)","Prefix inter- (between)","Regular and irregular comparison"],
    intro:"**-er** compares two things: tall → taller; **-est** compares three or more: tall → tallest. Learn the irregulars too: good → better → best. The prefixes **pre-** (before: preview) and **inter-** (between: international) show position in time and space." },
  { g:7, p:"VI", sem:"Two", icon:"🧪", src:"en:7:VI",
    title:"Nouns in -ment/-tion and the Roots bio-/auto-",
    sub:"Noun endings and Greek roots in everyday words",
    note:"**-ment** (movement) and **-tion** (action) make nouns; **bio-** means life (biology), **auto-** means self (autograph).",
    focus:["The -ment noun ending","The -tion noun ending","Root bio- (life)","Root auto- (self)"],
    intro:"**-ment** makes nouns: move → movement, agree → agreement; **-tion** makes nouns: act → action, invent → invention. The Greek roots **bio-** (life) and **auto-** (self) appear in biology, biography, automobile and autograph." },

  /* ================================ GRADE 8 ================================ */
  { g:8, p:"I", sem:"One", icon:"👤", src:"en:8:I",
    title:"Person Nouns in -ist and Abstract Nouns in -ence/-ance",
    sub:"Endings for people and for ideas and qualities",
    note:"**-ist** names a person (journalist); **-ence** / **-ance** make abstract nouns (difference, acceptance); **con-** means together.",
    focus:["The -ist person ending","-ence and -ance nouns","Prefix con- (with)","Abstract nouns"],
    intro:"**-ist** names a person: journal → journalist, science → scientist. **-ence** and **-ance** make abstract nouns: differ → difference, accept → acceptance. **con-** means with or together: con + dense = condense, make together." },
  { g:8, p:"II", sem:"One", icon:"🔊", src:"en:8:II",
    title:"Prefix hyper-, Adjectives in -ic and Sound Words",
    sub:"Words of degree, adjectives and words that echo sounds",
    note:"**hyper-** means over or beyond (hyperactive); **-ic** makes adjectives (heroic); **onomatopoeic** words imitate sounds (buzz, crash).",
    focus:["Prefix hyper- (over)","The -ic adjective ending","Onomatopoeia","Sound and spelling together"],
    intro:"**hyper-** means over or beyond: hyper + active = hyperactive. **-ic** makes adjectives: hero → heroic, history → historic. **Onomatopoeic** words imitate sounds: buzz, crash, splash. Say the sound, then check the spelling that makes it." },
  { g:8, p:"III", sem:"One", icon:"🏺", src:"en:8:III",
    title:"Nouns in -ism, Endings -ary/-ory and Prefixes ap-/ad-",
    sub:"Words of practice, place and direction",
    note:"**-ism** names a practice or idea (realism); **-ary** / **-ory** end nouns and adjectives (library, victory); **ap-** / **ad-** mean to or toward.",
    focus:["The -ism ending","-ary and -ory endings","Prefixes ap- and ad-","Words of idea, place and direction"],
    intro:"**-ism** names a practice, belief or idea: real → realism, hero → heroism. **-ary** (library, ordinary) and **-ory** (victory, history) are common endings. The prefixes **ap-** and **ad-** mean to or toward: ap + prove = approve; ad + ject = adjective." },
  { g:8, p:"IV", sem:"Two", icon:"🎬", src:"en:8:IV",
    title:"Verb Forms -ing and -ed with the Root -ology",
    sub:"Participles and the root meaning the study of",
    note:"**-ing** and **-ed** form participles (reading, walked); **-ology** means the study of (biology, psychology).",
    focus:["The -ing form","The -ed form","Root -ology (study of)","Participle endings"],
    intro:"**-ing** and **-ed** are the participle endings: read → reading, has read; walk → walked. Use -ing for action going on and -ed for the past. The root **-ology** means the study of: bio + logy = biology; psych + ology = psychology." },
  { g:8, p:"V", sem:"Two", icon:"🌊", src:"en:8:V",
    title:"Prefix sub-, Endings -ary and Alliterative Sounds",
    sub:"Position prefixes, common endings and sound patterns in prose",
    note:"**sub-** means under (submarine); **-ary** (dictionary) is a common ending; **alliteration** repeats the same first sound (sea shells).",
    focus:["Prefix sub- (under)","The -ary ending","Alliteration","Sound patterns in reading"],
    intro:"**sub-** means under: sub + marine = submarine, sub + merge = submerge. **-ary** ends many nouns and adjectives: dictionary, ordinary, temporary. **Alliteration** repeats the same first sound for effect: the sea shells were smooth." },
  { g:8, p:"VI", sem:"Two", icon:"🗣️", src:"en:8:VI",
    title:"Words of Debate in -tion, Prefix re- and Adjectives -ive",
    sub:"Argument vocabulary and word building",
    note:"**-tion** builds debate words (discussion, conclusion); **re-** means again or back (return); **-ive** makes adjectives (effective).",
    focus:["-tion in debate words","Prefix re- (back/again)","The -ive ending","Argument vocabulary"],
    intro:"**-tion** builds the vocabulary of argument: discuss → discussion, conclude → conclusion, persuade → persuasion. **re-** means again or back: turn → return, new → renew. **-ive** makes adjectives: effect → effective, act → active." },

  /* ================================ GRADE 9 ================================ */
  { g:9, p:"I", sem:"One", icon:"⏰", src:"en:9:I",
    title:"Roots chron- and trans- with Nouns in -ence",
    sub:"Roots of time and across, and abstract noun endings",
    note:"**chron-** means time (chronology); **trans-** means across (transport); **-ence** makes abstract nouns (confidence).",
    focus:["Root chron- (time)","Prefix trans- (across)","-ence abstract nouns","Roots in academic words"],
    intro:"**chron-** means time: chrono + logy = chronology, the order of time. **trans-** means across: trans + port = transport, carry across. **-ence** makes abstract nouns: confide → confidence, differ → difference." },
  { g:9, p:"II", sem:"One", icon:"🖼️", src:"en:9:II",
    title:"Root auto-, the Root -graphy and Endings -ent/-ant",
    sub:"Writing roots and adjective endings",
    note:"**auto-** means self (autograph); **-graphy** means writing (photography); **-ent** / **-ant** end adjectives (different, important).",
    focus:["Root auto- (self)","Root -graphy (writing)","-ent and -ant endings","Roots in compound words"],
    intro:"**auto-** means self: auto + graph = autograph, one's own writing. **-graphy** means writing: photo + graphy = photography. The endings **-ent** (different, confident) and **-ant** (important, elegant) finish many adjectives." },
  { g:9, p:"III", sem:"One", icon:"✉️", src:"en:9:III",
    title:"Formal Vocabulary, Prefixes in-/en- and Endings -ible/-able",
    sub:"Words of correspondence, direction and possibility",
    note:"**-ary** ends formal letter words (ordinary, necessary); **in-** / **en-** mean in or into (inside, enable); **-ible** / **-able** mean can be.",
    focus:["-ary in formal words","Prefixes in- and en-","-ible and -able","Formal vocabulary"],
    intro:"**-ary** finishes many formal words: ordinary, necessary, temporary. **in-** and **en-** mean in or into: in + side = inside; en + able = enable. **-ible** and **-able** mean can be: visible, readable." },
  { g:9, p:"IV", sem:"Two", icon:"📜", src:"en:9:IV",
    title:"Prefix ex-, Endings -ory and -ive in Kinds of Writing",
    sub:"Words of direction and the vocabulary of writing types",
    note:"**ex-** means out (export); **-ory** (descriptive) and **-ive** (narrative, persuasive) are adjective endings.",
    focus:["Prefix ex- (out)","The -ory ending","-ive in writing types","Vocabulary of composition"],
    intro:"**ex-** means out: ex + port = export, carry out; ex + tract = extract, pull out. **-ory** makes adjectives: describe → descriptive. **-ive** names the kinds of writing: narrate → narrative, persuade → persuasive, expound → expository." },
  { g:9, p:"V", sem:"Two", icon:"🎭", src:"en:9:V",
    title:"Drama Words in -edy, the Roots dyn-/stat- and Nouns in -ization",
    sub:"Genre vocabulary and roots of power and standing",
    note:"**-edy** ends drama words (comedy, tragedy); **dyn-** means power (dynamic), **stat-** means standing (static); **-ization** names processes.",
    focus:["Drama endings -edy","Roots dyn- and stat-","Nouns in -ization","Genre and process vocabulary"],
    intro:"**-edy** ends kinds of drama: com + edy = comedy; trag + edy = tragedy. **dyn-** means power: dyn + amic = dynamic. **stat-** means standing: stat + ic = static. **-ization** names a process: organise → organisation, modernise → modernisation." },
  { g:9, p:"VI", sem:"Two", icon:"⚔️", src:"en:9:VI",
    title:"Prefixes counter-, ob- and sub- with Nouns in -sion",
    sub:"Prefixes of against, toward and under",
    note:"**counter-** means against (counteract); **ob-** (object) and **sub-** (submerge) mean toward and under; **-sion** makes nouns (division).",
    focus:["Prefix counter- (against)","Prefix ob- (toward)","Prefix sub- (under)","Nouns in -sion"],
    intro:"**counter-** means against: counter + act = counteract. **ob-** means toward: ob + ject = object. **sub-** means under: sub + merge = submerge. The ending **-sion** makes nouns: divide → division, conclude → conclusion." },

  /* ================================ GRADE 10 ================================ */
  { g:10, p:"I", sem:"One", icon:"🧱", src:"eg:10:I",
    title:"Nouns by Suffix: -ness, -ment, -tion and -ship",
    sub:"Building nouns from adjectives and verbs",
    note:"**-ness** (kindness), **-ment** (government), **-tion** (education) and **-ship** (friendship) are the noun suffixes of this period.",
    focus:["The -ness suffix","The -ment suffix","The -tion suffix","The -ship suffix"],
    intro:"Suffixes build nouns from other words. **-ness** builds nouns from adjectives: kind → kindness, dark → darkness. **-ment** builds nouns from verbs: govern → government, agree → agreement. **-tion** (educate → education) and **-ship** (friend → friendship) are the other two patterns of this period." },
  { g:10, p:"II", sem:"One", icon:"🔧", src:"eg:10:II",
    title:"Verb Building: -ise, en-, -ify and re-",
    sub:"Making verbs and changing their meaning",
    note:"**-ise** (realise) and **-ify** (beautify) make verbs; **en-** (enable) and **re-** (rewrite) are verb prefixes.",
    focus:["The -ise verb suffix","The -ify verb suffix","Prefix en-","Prefix re- (again)"],
    intro:"Verbs are built with suffixes and prefixes. **-ise** makes verbs: real → realise; **-ify** makes verbs: beauty → beautify. **en-** means make or put into: able → enable; **re-** means again: write → rewrite." },
  { g:10, p:"III", sem:"One", icon:"⚖️", src:"eg:10:III",
    title:"Verb Forms, Comparisons and the Prefix over-",
    sub:"Making verbs from adjectives and comparing with over-",
    note:"**-en** makes verbs (widen); **-er** / **-est** compare (younger, youngest); **over-** means too much (overcook).",
    focus:["The -en verb suffix","-er and -est comparison","Prefix over-","Form and meaning"],
    intro:"**-en** makes verbs from adjectives: wide → widen, soft → soften. **-er** compares two, **-est** more than two: young → younger → youngest. **over-** means too much: over + cook = overcook, cook too much." },
  { g:10, p:"IV", sem:"Two", icon:"🎨", src:"eg:10:IV",
    title:"Adjectives and Adverbs: -ly, -ful, -less and -ous",
    sub:"The suffixes that make describing words",
    note:"**-ly** makes adverbs (quickly); **-ful** (useful), **-less** (useless) and **-ous** (famous) make adjectives.",
    focus:["The -ly suffix","-ful and -less suffixes","The -ous suffix","Adjectives and adverbs"],
    intro:"**-ly** makes adverbs from adjectives: quick → quickly. **-ful** means full of: use → useful; **-less** means without: use → useless. **-ous** means having the quality of: fame → famous." },
  { g:10, p:"V", sem:"Two", icon:"🗺️", src:"eg:10:V",
    title:"Prefixes of Position: inter-, sub-, co- and trans-",
    sub:"Prefixes of between, under, together and across",
    note:"**inter-** means between (international), **sub-** under (submarine), **co-** together (cooperate), **trans-** across (transport).",
    focus:["Prefix inter- (between)","Prefix sub- (under)","Prefix co- (together)","Prefix trans- (across)"],
    intro:"These four prefixes show position and direction. **inter-** means between: inter + national = international. **sub-** means under: sub + marine = submarine. **co-** means together: co + operate = cooperate. **trans-** means across: trans + port = transport." },
  { g:10, p:"VI", sem:"Two", icon:"🔗", src:"eg:10:VI",
    title:"Phrasal Patterns: break, run, get and put",
    sub:"Word parts that change meaning with particles",
    note:"**break**, **run**, **get** and **put** combine with small words to make phrasal verbs: break down, run out, get up, put off.",
    focus:["Phrasal verbs with break","Phrasal verbs with run","Phrasal verbs with get","Phrasal verbs with put"],
    intro:"Some of the most useful word patterns are **phrasal verbs** — a verb plus a small word. Break down, break out, break even; run out, run into, run after; get up, get over, get along; put off, put on, put up. The small word changes the meaning." },

  /* ================================ GRADE 11 ================================ */
  { g:11, p:"I", sem:"One", icon:"📏", src:"eg:11:I",
    title:"Spelling Rules: Doubling, Dropping e, -ies and the Prefix pre-",
    sub:"The rules for adding endings correctly",
    note:"**Double** the final consonant (running), **drop e** before -ing (making), change y to **-ies** (carries), and **pre-** means before.",
    focus:["Doubling the final consonant","Dropping silent e","-ies from y","Prefix pre- (before)"],
    intro:"Correct spelling follows rules. Double the final consonant when you add -ing or -ed: run → running. Drop the silent e before -ing: make → making. Change y to i before -es: carry → carries. **pre-** means before: pre + view = preview." },
  { g:11, p:"II", sem:"One", icon:"🔍", src:"eg:11:II",
    title:"Spelling Choices: -ible/-able and Silent Letters",
    sub:"Two adjective endings and letters we do not say",
    note:"**-ible** (visible) and **-able** (readable) mean can be; **silent letters** (debt, knee, write) are written but not sounded.",
    focus:["-ible and -able endings","Choosing the right ending","Silent letters","Spelling and pronunciation"],
    intro:"**-ible** and **-able** both mean can be, but the spelling must be learned: visible, possible, flexible; readable, comfortable, valuable. **Silent letters** are written but not sounded: the b in debt, the k in knee, the w in write." },
  { g:11, p:"III", sem:"One", icon:"🏺", src:"eg:11:III",
    title:"Latin Roots: scrib, dict, spect and port",
    sub:"The roots that build many English words",
    note:"**scrib** means write (describe), **dict** say (predict), **spect** look (inspect), **port** carry (export).",
    focus:["Root scrib (write)","Root dict (say)","Root spect (look)","Root port (carry)"],
    intro:"Latin roots build large word families. **scrib** means write: describe, prescribe, manuscript. **dict** means say: predict, dictate, dictionary. **spect** means look: inspect, respect, spectator. **port** means carry: export, import, transport." },
  { g:11, p:"IV", sem:"Two", icon:"📖", src:"eg:11:IV",
    title:"Word Building: un-, dis-, -tion and the Root graph",
    sub:"Prefixes of not/opposite and the root of writing",
    note:"**un-** means not (unfair), **dis-** means opposite (disagree), **-tion** makes nouns (action), **graph** means write (autograph).",
    focus:["Prefix un-","Prefix dis-","The -tion noun suffix","Root graph (write)"],
    intro:"**un-** means not: fair → unfair. **dis-** gives the opposite: agree → disagree. **-tion** makes nouns: act → action. The root **graph** means write: auto + graph = autograph; photo + graph = photograph." },
  { g:11, p:"V", sem:"Two", icon:"🔭", src:"eg:11:V",
    title:"Roots of Knowledge: log, bibl with re- and -ary",
    sub:"Roots of word, book and study",
    note:"**log** means word or study (dialogue), **bibl** means book (bibliography), **re-** means again (review), **-ary** ends adjectives and nouns.",
    focus:["Root log (word/study)","Root bibl (book)","Prefix re- (again)","The -ary ending"],
    intro:"**log** means word or study: dia + logue = dialogue; bio + logy = biology. **bibl** means book: biblio + graphy = bibliography. **re-** means again: re + view = review. **-ary** ends many nouns and adjectives: dictionary, temporary." },
  { g:11, p:"VI", sem:"Two", icon:"✉️", src:"eg:11:VI",
    title:"Nouns and Adjectives: -ment, -ance, in- and Formal Word Study",
    sub:"Noun endings and the prefix of not",
    note:"**-ment** (government) and **-ance** (importance) make nouns; **in-** means not (invisible); formal vocabulary belongs to letters and reports.",
    focus:["The -ment suffix","The -ance suffix","Prefix in- (not)","Formal word study"],
    intro:"**-ment** makes nouns: govern → government; **-ance** makes nouns: important → importance. **in-** means not: visible → invisible, correct → incorrect. The formal vocabulary of this period belongs to letters and reports: application, reference, enclosure." },

  /* ================================ GRADE 12 ================================ */
  { g:12, p:"I", sem:"One", icon:"✒️", src:"eg:12:I",
    title:"Apostrophe Spelling, the -ory Ending and the Roots pro-, voc",
    sub:"Contractions, possessives and roots of forward/voice",
    note:"**Apostrophes** show contractions (don't) and possession (Musu's); **-ory** ends nouns and adjectives (victory, advisory); **pro-** means forward, **voc** means voice or call.",
    focus:["Apostrophes: contractions","Apostrophes: possessives","The -ory ending","Roots pro- and voc"],
    intro:"An **apostrophe** shows missing letters in contractions — do not → don't — and belonging in possessives — Musu's book. **-ory** ends nouns and adjectives: victory, compulsory. **pro-** means forward: pro + mote = promote; **voc** means voice or call: voc + al = vocal." },
  { g:12, p:"II", sem:"One", icon:"🏛️", src:"eg:12:II",
    title:"Greek Roots and Word Families: -ist, -ism and vers",
    sub:"Roots and suffixes for people, ideas and turning",
    note:"**Greek roots** build many learning words; **-ist** names a person (artist); **-ism** names an idea (realism); **vers** means turn (reverse).",
    focus:["Greek roots in English","The -ist suffix","The -ism suffix","Root vers (turn)"],
    intro:"Greek roots build the vocabulary of learning: philo + sophy = philosophy, geo + graphy = geography. **-ist** names a person: art → artist. **-ism** names an idea or practice: real → realism. **vers** means turn: re + verse = reverse." },
  { g:12, p:"III", sem:"Two", icon:"🔗", src:"eg:12:III",
    title:"Phrasal Verbs: take, give, look and come",
    sub:"Verb + particle patterns for advanced usage",
    note:"**take** (take off, take over), **give** (give up), **look** (look after), **come** (come across) are key phrasal patterns.",
    focus:["Phrasal verbs with take","Phrasal verbs with give","Phrasal verbs with look","Phrasal verbs with come"],
    intro:"Phrasal verbs change meaning with each particle. Take off (remove or leave), take over (control); give up (stop), give in (surrender); look after (care for), look into (investigate); come across (find by chance), come up (arise). Learn the particle with each verb." },
  { g:12, p:"IV", sem:"Two", icon:"🧱", src:"eg:12:IV",
    title:"Word Formation: -ive, -ity, con- and the Root struct",
    sub:"Adjective and noun suffixes with the root of building",
    note:"**-ive** (creative) and **-ity** (creativity) build adjectives and nouns; **con-** means together; **struct** means build (construct).",
    focus:["The -ive suffix","The -ity suffix","Prefix con- (together)","Root struct (build)"],
    intro:"**-ive** makes adjectives: create → creative; **-ity** makes nouns: creative → creativity. **con-** means together: con + struct = construct, build together. The root **struct** builds structure, instruction and construction." },
  { g:12, p:"V", sem:"Two", icon:"📏", src:"eg:12:V",
    title:"Spelling Rules: Doubling, ie/ei, -ence and -ant",
    sub:"Final spelling rules for accuracy",
    note:"**Double** consonants after short vowels (beginning); **i before e** except after c (receive); **-ence** (difference) and **-ant** (important) are common endings.",
    focus:["Doubling after short vowels","ie/ei rule","The -ence ending","The -ant ending"],
    intro:"Final spelling checks: double the consonant after a short vowel when the stress is final — begin → beginning. The rule for ie/ei: i before e except after c — believe, receive. **-ence** (difference) and **-ant** (important) are common endings; learn each word." },
  { g:12, p:"VI", sem:"Two", icon:"🎓", src:"eg:12:VI",
    title:"Exam Word Study: Plurals, Commands, Spelling and Connectives",
    sub:"The word patterns that carry marks in the WASSCE",
    note:"Review **plurals** (child → children), **commands** (imperatives), **spelling** rules and **connectives** (however, therefore) for the examination.",
    focus:["Forming plurals","Imperative (command) forms","Examination spelling","Connectives"],
    intro:"Before the examination, review the word patterns that carry marks. Form **plurals** correctly: child → children, leaf → leaves. Use **commands** (imperatives): Stop! Listen! The spelling of common words must be exact. **Connectives** join ideas: however, therefore, in addition." }
];

/* ---- shared band support: outcomes, objectives, activities, materials ----
   The same course is taught across a whole band, so the teaching support is
   shared per band; the patterns themselves change every period. */
var PHO_BAND = {
  el: {
    outcomes:["Learners are able to apply letter-sound knowledge to read and spell words with the sounds and patterns of this period."],
    objectives:[
      "Say the name and sound of each letter or pattern in this period",
      "Blend the sounds of a word from left to right to read it",
      "Segment a word into its sounds to spell it",
      "Write two more words of your own for every pattern"
    ],
    steps:[
      "Say the pattern sound first, then read each example word aloud.",
      "Blend the sounds from left to right: /c/ – /a/ – /t/ → cat.",
      "Segment the word slowly, one finger for every sound, to spell it.",
      "Sort the words by pattern and add two words of your own to each family."
    ],
    activities:["Sound the letters and words aloud in chorus","Blend and segment words with the teacher's help","Sort example words into pattern families","Dictate and check the spelling of the new words"],
    materials:["Letter and word cards","Flashcards of the patterns","Alphabet chart","Exercise books and pencils"],
    assessment:["Oral reading and sound checks","Written exercises and dictation","Homework"]
  },
  jh: {
    outcomes:["Learners are able to use word structure — prefixes, suffixes and word roots — to read, spell and understand new words."],
    objectives:[
      "Identify each spelling pattern and read the example words",
      "Sort words by their pattern and say what the pattern adds",
      "Spell the period's words correctly and use them in sentences",
      "Build new words with the same prefixes, suffixes or roots"
    ],
    steps:[
      "Read each word and underline the pattern letters.",
      "Separate the word into syllables and say each part clearly.",
      "Cover the prefix or ending, read the base word, then the whole word.",
      "Add two new words of your own to every pattern."
    ],
    activities:["Underline the pattern letters in each example word","Sort words by prefix, suffix or root","Dictation and self-check with the answer key","Build new words using the same patterns"],
    materials:["Word cards and pattern strips","Exercise books and dictionaries","Teacher's answer key"],
    assessment:["Pattern sorting and spelling tests","Written exercises","Homework and dictation"]
  },
  sh: {
    outcomes:["Learners are able to analyse words into their meaningful parts and use that knowledge to spell, pronounce and define the vocabulary they meet."],
    objectives:[
      "Identify the word-building pattern and say what it contributes",
      "Analyse each example word into root, prefix and suffix",
      "Spell and use the period's words correctly in writing",
      "Build and define new words that use the same pattern"
    ],
    steps:[
      "Separate each word into its meaningful parts — root, prefix, suffix.",
      "Say what each part contributes to the meaning of the whole word.",
      "Use the word in a sentence and check the spelling against the pattern.",
      "Build two new words with the same pattern and define them."
    ],
    activities:["Analyse words into root, prefix and suffix","Word-building race using the period's patterns","Use new words in sentences and check spelling","Root-meaning matching activities"],
    materials:["Word lists and dictionaries","Exercise books","Teacher's answer key","WASSCE-style word-building questions"],
    assessment:["Word-building exercises","Spelling and usage tests","Dictation and mock questions"]
  }
};

/* ---- per-grade teaching tips, used on every Study Notes page ---- */
var PHO_TIPS = {
  1:"**Teaching tip:** Say every sound slowly and clearly; have the class echo it, then blend the sounds into the whole word.",
  2:"**Teaching tip:** Read each word aloud first, then ask pupils to find the pattern letters and say what the two letters do together.",
  3:"**Teaching tip:** Use the pattern families as spelling lists — but ask pupils to say the word, then write it, then check it.",
  4:"**Teaching tip:** Ask pupils to sort words into families and explain the rule they used; sorting makes the spelling stick.",
  5:"**Teaching tip:** Whenever two spellings make one sound, give both spellings with a small word pair and let the pupils say both aloud.",
  6:"**Teaching tip:** For longer words, teach the chunks first — read the base, read the ending, then read the whole word.",
  7:"**Teaching tip:** Cover the prefix or suffix, read the base word, then read the whole word and say what the pattern added.",
  8:"**Teaching tip:** Ask pupils to build a word with each pattern and say what the pattern contributes to the meaning.",
  9:"**Teaching tip:** Use the roots to make word families on the board; every family member shares the root's meaning.",
  10:"**Teaching tip:** Give the suffix and the base; pupils must say what word is built and what the pattern adds.",
  11:"**Teaching tip:** Dictate the pattern words, then have pupils self-mark; each reason is in the answer key.",
  12:"**Teaching tip:** Revise the patterns through exam-style questions: choose the correct spelling, form the plural, complete the word."
};

/* ---- build the Phonics curriculum from the official pattern lists ----
   The source unit supplies the OFFICIAL phonics[] pattern list, word list and
   sight words. The unit's title, note, focus list and study text are the
   focused phonics teaching text for the period. */
var PHO_CURRICULUM = (function () {
  function sourceUnit(ref) {
    var b = ref.split(":");
    var arr = b[0] === "eg" ? EG_CURRICULUM : EN_CURRICULUM;
    for (var i = 0; i < arr.length; i++) {
      if (arr[i].grade === +b[1] && arr[i].period === b[2]) return arr[i];
    }
    throw new Error("Phonics source unit not found: " + ref);
  }
  function bandOf(g) { return g <= 6 ? "el" : g <= 9 ? "jh" : "sh"; }
  return PHO_UNITS.map(function (m) {
    var src = sourceUnit(m.src), B = PHO_BAND[bandOf(m.g)];
    var rows = (src.phonics || []).map(function (p) {
      return [p.p, p.label, p.words.slice(0, 6).join(", ")];
    });
    return {
      grade: m.g, period: m.p, sem: m.sem, icon: m.icon,
      title: m.title, subtitle: m.sub,
      outcomes: B.outcomes, objectives: B.objectives,
      note: m.note,
      study: [
        { k: "h3", t: "The Sounds and Patterns of this Period" },
        { k: "p", t: m.intro },
        { k: "table", head: ["Pattern / sound", "What it says", "Example words"], rows: rows },
        { k: "rule" },
        { k: "h3", t: "How to Read and Spell the Words" },
        { k: "bul", items: B.steps },
        { k: "p", t: PHO_TIPS[m.g] }
      ],
      focus: m.focus,
      phonics: src.phonics || [],
      words: src.words || [],
      sight: src.sight || [],
      activities: B.activities,
      materials: B.materials,
      assessment: B.assessment
    };
  });
})();
